asset: pgslice-apple-darwin
tap: Blissfully/homebrew-tools/pgslice.rb
template: >
  class PGSlice < Formula
    desc     "$REPO_DESCRIPTION"
    homepage "$REPO_WEBITE"
    version  "$STABLE_VERSION"
    url      "$STABLE_ASSET_URL"
    sha256   "$STABLE_ASSET_SHA256"

    def install
      prefix.install "pgslice"
    end
  end
