asset: pg_parcel-apple-darwin
tap: Blissfully/homebrew-tools/pg_parcel.rb
template: >
  class pg_parcel < Formula
    desc     "$REPO_DESCRIPTION"
    homepage "$REPO_WEBITE"
    version  "$STABLE_VERSION"
    url      "$STABLE_ASSET_URL"
    sha256   "$STABLE_ASSET_SHA256"

    def install
      prefix.install "pg_parcel"
    end
  end
