[package]
name = "pgslice"
version = "0.1.0"
edition = "2021"

[dependencies]
postgres = "0.19.2"
lazy_static = "1.4.0"
dialoguer = "0.10.0"
indicatif = "0.16.2"
clap = { version = "3.1.5", features = ["derive"] }